## Lendo bibliotecas

In [1]:
import math
import numpy as np
import pandas as pd
%config Completer.use_jedi = False # this speeds up autocomplete

## Entendendo o problema

In [9]:
# Criando nome dos robôs
nome_robos = ['asea_irb', 'cincinatti', 'cybotech',
             'hitachi', 'unimation', 'us_robots', 'yaskawa']
# Criando matriz com valores dos robôs
matriz = [
    [60, 0.40, 2540, 500, 990],
    [6.35, 0.15, 1016, 3000, 1041],
    [6.8, 0.10, 1727.2, 1500, 1676],
    [10, 0.20, 1000, 2000, 965],
    [2.5, 0.10, 560, 500, 915],
    [4.5, 0.08, 1016, 350, 508],
    [3, 0.10, 177, 1000, 920]
]

# Criando nome das colunas
nome_colunas = ['load_capacity', 'repeatability',
                'maximum tip speed', 'memory capacity', 'manipulator reach'
               ]

# Transformando matriz em dataframe
df = pd.DataFrame(matriz, columns = nome_colunas, index = nome_robos)
df

load_capacity  repeatability  maximum tip speed  memory capacity  \
asea_irb            60.00           0.40             2540.0              500   
cincinatti           6.35           0.15             1016.0             3000   
cybotech             6.80           0.10             1727.2             1500   
hitachi             10.00           0.20             1000.0             2000   
unimation            2.50           0.10              560.0              500   
us_robots            4.50           0.08             1016.0              350   
yaskawa              3.00           0.10              177.0             1000   

            manipulator reach  
asea_irb                  990  
cincinatti               1041  
cybotech                 1676  
hitachi                   965  
unimation                 915  
us_robots                 508  
yaskawa                   920

In [10]:
matriz = np.array(matriz).T
matriz

array([[6.0000e+01, 6.3500e+00, 6.8000e+00, 1.0000e+01, 2.5000e+00,
        4.5000e+00, 3.0000e+00],
       [4.0000e-01, 1.5000e-01, 1.0000e-01, 2.0000e-01, 1.0000e-01,
        8.0000e-02, 1.0000e-01],
       [2.5400e+03, 1.0160e+03, 1.7272e+03, 1.0000e+03, 5.6000e+02,
        1.0160e+03, 1.7700e+02],
       [5.0000e+02, 3.0000e+03, 1.5000e+03, 2.0000e+03, 5.0000e+02,
        3.5000e+02, 1.0000e+03],
       [9.9000e+02, 1.0410e+03, 1.6760e+03, 9.6500e+02, 9.1500e+02,
        5.0800e+02, 9.2000e+02]])

In [11]:
# Criando matriz de pesos
pesos = [0.036, 0.192, 0.326, 0.326, 0.120]

In [ ]:
'''
Fórmula Normalização - Parte 1:
i = 0
j = 0
m[i][j] / math.sqrt(
    sum(
        [math.pow(m[i][j], 2), math.pow(m[i+1][j], 2), math.pow(m[i+2][j], 2), math.pow(m[i+3][j], 2),
         math.pow(m[i+4][j], 2), math.pow(m[i+5][j], 2), math.pow(m[i+6][j], 2)])
)

Dessa vez, nós estamos começando com i = 0 e aumentando em 1 o j.
O problema é o denominador.
Se nós tivéssemos uma só linha com todos os valores da linha naquela coluna, bastaria elevar essa linha ao quadrado.

Fórmula Normalização - Parte 2:

i = 0
j = 0
caso = m[i][j]
denominador = math.sqrt(sum(math.pow(m[i], 2)))
normalizado = caso / denominador

Assim, se a linha for o nosso objeto de interesse, avançamos para o segundo caso andando com j+1.
Em relação a pesos, a coluna deverá ser indicada com o mesmo índice da linha usado acima.
Ficaria:
peso[i]

Assim, o caso 3 da primeira linha, que é da primeira coluna, terá index peso[i], indicando ser da primeira coluna.
'''

### Criando Tabela 4: Normalized Matrix

In [12]:
# Inicializando matrizes
norm_matrix = []

# Criando função
for i in range(0, np.shape(matriz)[0]):
    for j in range(0, np.shape(matriz)[1]):

        caso = matriz[i][j]
        denominador = math.sqrt(sum(np.power(matriz[i], 2)))
        normalizado = caso / denominador
    
        norm_matrix.append(normalizado)
        
        j += 1
        
# Organizando matriz
norm_matrix = np.array(norm_matrix)
norm_matrix = np.reshape(norm_matrix, (5, 7)).T
norm_matrix = norm_matrix.round(4)

In [13]:
# Print da matriz
print(norm_matrix)

[[0.9705 0.7861 0.7087 0.1217 0.3557]
 [0.1027 0.2948 0.2835 0.7304 0.374 ]
 [0.11   0.1965 0.4819 0.3652 0.6022]
 [0.1618 0.3931 0.279  0.4869 0.3467]
 [0.0404 0.1965 0.1563 0.1217 0.3288]
 [0.0728 0.1572 0.2835 0.0852 0.1825]
 [0.0485 0.1965 0.0494 0.2435 0.3306]]


### Criando Tabela 5: Weighted Normalized Matrix

In [7]:
weighted_matrix = norm_matrix * pesos

print(weighted_matrix)

[[0.034938  0.1509312 0.2310362 0.0396742 0.042684 ]
 [0.0036972 0.0566016 0.092421  0.2381104 0.04488  ]
 [0.00396   0.037728  0.1570994 0.1190552 0.072264 ]
 [0.0058248 0.0754752 0.090954  0.1587294 0.041604 ]
 [0.0014544 0.037728  0.0509538 0.0396742 0.039456 ]
 [0.0026208 0.0301824 0.092421  0.0277752 0.0219   ]
 [0.001746  0.037728  0.0161044 0.079381  0.039672 ]]


### Criando Tabela 6: Concordance Matrix

In [ ]:
'''
[[60,    0.4,   2540,  500,  990],
 [6.35, 0.15,   1016, 3000, 1041],
 [6.8,   0.1, 1727.2, 1500, 1676],
 [10,    0.2,   1000, 2000,  965],
 [2.5,   0.1,    560,  500,  915],
 [4.5,  0.08,   1016,  350,  508],
 [3,     0.1,    177, 1000,  920]]

Começamos pegando o primeiro elemento da matriz e comparando com o primeiro.
O resultado deve ser igual a "1", que logo será substituído por outro valor.

Ou seja:
caso = matriz[i][j]
caso_comp = matriz_duplic[i][k]

Se:
j == k? SIM. -> 1

A partir daqui, aumentamos o número de k em 1 APENAS para a matriz_duplic.
k += 1
i permanece o mesmo (0). j permance o mesmo (0).

Se
j == k? NÃO:

caso >= caso_comp? SIM.

A condição SIM vai abrir lugar para a gente começar a soma de valores.
Se sim, pesos[k] deve ser adicionado a uma lista temporária.

temp.append(pesos[i])

Por que 'i'? Porque 'i' irá nos indicar em qual coluna de 'pesos' estamos.
Agora, andamos uma casa para a direita em cada linha.

Assim,
i += 1
k = 1
j = 0

Novamente, se testa se matriz[i][j] == matriz[i][k]
Nessa primeira situação, se o valor de caso == caso_comp.

caso >= caso_comp? SIM.

Assim,

temp.append(pesos[i]) é novamente acionado.

Continuando,
j += 1
k = 1
i = 0

Novamente, testa-se:
caso >= caso_comp? SIM.

Se sim,

temp.append(pesos[j])

Isso acontece até que j == np.append(matriz)[1]
...
O mesmo acontece até que k =

'''

In [21]:
# Comparação 0, quando j == k, resultando em '-'
i = 0
j = 0
k = 0 

caso = matriz[i][j]
caso_comp = matriz[i][k]
print(caso, caso_comp)

60.0 60.0


In [17]:
# Primeira comparação real, resultando em pesos[i]
i = 0
j = 0
k = 1 # k += 1

caso = matriz[i][j]
caso_comp = matriz[i][k]
print(caso, caso_comp)

60.0 6.35


In [19]:
# Segunda comparação real, resultando em pesos[i]
i = 1 # i += 1
j = 0 
k = 1

caso = matriz[i][j]
caso_comp = matriz[i][k]
print(caso, caso_comp)

0.4 0.15


In [27]:
# Terceira comparação real, resultando em pesos[i]
i = 2 # i += 1
j = 0 
k = 1

caso = matriz[i][j]
caso_comp = matriz_dup[i][k]
print(caso, caso_comp)

2540.0 1016.0


In [28]:
# Quarta comparação real, resultando em pesos[i]
i = 3 # i += 1
j = 0 
k = 1

caso = matriz[i][j]
caso_comp = matriz_dup[i][k]
print(caso, caso_comp)

500.0 3000.0


In [30]:
# Quinta comparação real, resultando em pesos[i]
i = 4 # i += 1
j = 0 
k = 1

caso = matriz[i][j]
caso_comp = matriz_dup[i][k]
print(caso, caso_comp)

990.0 1041.0


In [24]:
# Quinta comparação real, resultando em pesos[i]
# Aqui, a gente vê que i == np.shape(matriz)[0]
# Quando isso acontece, j += 1 e i volta a ser 0 e k volta a ser 0
i = 0 # 0
j = 1 # j += 1 
k = 0 # 0

caso = matriz[i][j]
caso_comp = matriz[i][k]
print(caso, caso_comp)

6.35 60.0


In [22]:
np.shape(matriz)[0]

5

In [110]:
# Inicializando matrizes
conc_matrix = []

# Criando função
for j in range(0, np.shape(weighted_matrix)[1]):
    for k in range(0, np.shape(weighted_matrix)[1]):
        values = []
        
        if k == j:
            conc_matrix.append('-')
            k += 1
        
        else:
            for i in range(0, np.shape(weighted_matrix)[0]):
               
                caso = weighted_matrix[i][j]
                caso_comp = weighted_matrix[i][k]
            
                if caso >= caso_comp:
                    values.append(pesos[j])
                
                else:
                    continue
                
                conc_matrix.append(sum(values))

In [111]:
conc_matrix

['-',
 0.192,
 0.384,
 0.5760000000000001,
 0.768,
 0.96,
 1.152,
 1.3439999999999999,
 '-',
 0.192,
 0.192,
 0.384,
 0.192,
 0.384,
 0.5760000000000001,
 0.768,
 0.326,
 0.652,
 0.978,
 1.304,
 1.6300000000000001,
 1.9560000000000002,
 2.282,
 0.326,
 0.652,
 0.978,
 1.304,
 1.6300000000000001,
 1.9560000000000002,
 '-',
 0.326,
 0.652,
 0.978,
 1.304,
 0.326,
 0.652,
 0.978,
 1.304,
 1.6300000000000001,
 1.9560000000000002,
 0.326,
 0.652,
 0.978,
 1.304,
 1.6300000000000001,
 1.9560000000000002,
 2.282,
 0.326,
 0.652,
 0.978,
 1.304,
 1.6300000000000001,
 0.326,
 0.652,
 0.978,
 '-',
 0.326,
 0.652,
 0.978,
 1.304,
 1.6300000000000001,
 1.9560000000000002,
 0.12,
 0.24,
 0.36,
 0.48,
 0.6,
 0.72,
 0.84,
 0.12,
 0.24,
 0.36,
 0.12,
 0.12,
 '-']

In [97]:
# Inicializando matrizes
conc_matrix = []

# Criando função
for j in range(0, np.shape(weighted_matrix)[1]):
    values = []
    
    for i in range(0, np.shape(weighted_matrix)[0]):
        if j == k:
            conc_matrix.append(0)
            k += 1
        
        else:
            for k in range(i + 1, np.shape(weighted_matrix)[1]):
                caso = weighted_matrix[i][j]
                caso_comp = weighted_matrix[i][k]
            
                if caso >= caso_comp:
                    values.append(pesos[i])
                
                else:
                    continue
                
                conc_matrix.append(sum(values))

In [95]:
conc_matrix

[0.036,
 0.072,
 0.10799999999999998,
 0.3,
 0.626,
 0.036,
 0.072,
 0.10799999999999998,
 0.144,
 0.33599999999999997,
 0.528,
 0.8540000000000001,
 1.1800000000000002,
 1.5060000000000002,
 0.036,
 0.228,
 0.42000000000000004,
 0.6120000000000001,
 0.9380000000000002,
 1.2640000000000002,
 1.5900000000000003,
 0,
 0.192,
 0,
 0.518,
 0]

In [60]:
values = []

In [45]:
values = [0, 3, 10]

In [61]:
sum(values)

0

In [53]:
conc_matrix.append(sum(values))

In [54]:
print(conc_matrix)

[13, 13]
