## Lendo bibliotecas

In [1]:
import math
import numpy as np
import pandas as pd
%config Completer.use_jedi = False # this speeds up autocomplete

## Entendendo o problema

In [2]:
# Criando nome dos robôs
nome_robos = ['asea_irb', 'cincinatti', 'cybotech',
             'hitachi', 'unimation', 'us_robots', 'yaskawa']
# Criando matriz com valores dos robôs
matriz = [
    [60, 0.40, 2540, 500, 990],
    [6.35, 0.15, 1016, 3000, 1041],
    [6.8, 0.10, 1727.2, 1500, 1676],
    [10, 0.20, 1000, 2000, 965],
    [2.5, 0.10, 560, 500, 915],
    [4.5, 0.08, 1016, 350, 508],
    [3, 0.10, 177, 1000, 920]
]

# Criando nome das colunas
nome_colunas = ['load_capacity', 'repeatability',
                'maximum tip speed', 'memory capacity', 'manipulator reach'
               ]

# Transformando matriz em dataframe
df = pd.DataFrame(matriz, columns = nome_colunas, index = nome_robos)
df

load_capacity  repeatability  maximum tip speed  memory capacity  \
asea_irb            60.00           0.40             2540.0              500   
cincinatti           6.35           0.15             1016.0             3000   
cybotech             6.80           0.10             1727.2             1500   
hitachi             10.00           0.20             1000.0             2000   
unimation            2.50           0.10              560.0              500   
us_robots            4.50           0.08             1016.0              350   
yaskawa              3.00           0.10              177.0             1000   

            manipulator reach  
asea_irb                  990  
cincinatti               1041  
cybotech                 1676  
hitachi                   965  
unimation                 915  
us_robots                 508  
yaskawa                   920

In [3]:
matriz = np.array(matriz).T
matriz

array([[6.0000e+01, 6.3500e+00, 6.8000e+00, 1.0000e+01, 2.5000e+00,
        4.5000e+00, 3.0000e+00],
       [4.0000e-01, 1.5000e-01, 1.0000e-01, 2.0000e-01, 1.0000e-01,
        8.0000e-02, 1.0000e-01],
       [2.5400e+03, 1.0160e+03, 1.7272e+03, 1.0000e+03, 5.6000e+02,
        1.0160e+03, 1.7700e+02],
       [5.0000e+02, 3.0000e+03, 1.5000e+03, 2.0000e+03, 5.0000e+02,
        3.5000e+02, 1.0000e+03],
       [9.9000e+02, 1.0410e+03, 1.6760e+03, 9.6500e+02, 9.1500e+02,
        5.0800e+02, 9.2000e+02]])

In [4]:
# Criando matriz de pesos
pesos = [0.036, 0.192, 0.326, 0.326, 0.120]

### Criando Tabela 4: Normalized Matrix

In [6]:
# Inicializando matrizes
norm_matrix = []

# Criando função
for i in range(0, np.shape(matriz)[0]):
    for j in range(0, np.shape(matriz)[1]):

        caso = matriz[i][j]
        denominador = math.sqrt(sum(np.power(matriz[i], 2)))
        normalizado = caso / denominador
    
        norm_matrix.append(normalizado)
        
        j += 1
        
# Organizando matriz
norm_matrix = np.array(norm_matrix)
norm_matrix = np.reshape(norm_matrix, (5, 7)).T
norm_matrix = norm_matrix.round(4)

In [7]:
# Print da matriz
print(norm_matrix)

[[0.9705 0.7861 0.7087 0.1217 0.3557]
 [0.1027 0.2948 0.2835 0.7304 0.374 ]
 [0.11   0.1965 0.4819 0.3652 0.6022]
 [0.1618 0.3931 0.279  0.4869 0.3467]
 [0.0404 0.1965 0.1563 0.1217 0.3288]
 [0.0728 0.1572 0.2835 0.0852 0.1825]
 [0.0485 0.1965 0.0494 0.2435 0.3306]]


### Criando Tabela 5: Weighted Normalized Matrix

In [8]:
weighted_matrix = norm_matrix * pesos

print(weighted_matrix)

[[0.034938  0.1509312 0.2310362 0.0396742 0.042684 ]
 [0.0036972 0.0566016 0.092421  0.2381104 0.04488  ]
 [0.00396   0.037728  0.1570994 0.1190552 0.072264 ]
 [0.0058248 0.0754752 0.090954  0.1587294 0.041604 ]
 [0.0014544 0.037728  0.0509538 0.0396742 0.039456 ]
 [0.0026208 0.0301824 0.092421  0.0277752 0.0219   ]
 [0.001746  0.037728  0.0161044 0.079381  0.039672 ]]


### Criando Tabela 6: Concordance Matrix

In [141]:
# Inicializando matrizes
conc_matrix = []

# Criando função
for j in range(0, np.shape(weighted_matrix)[0]):
    for k in range(0, np.shape(weighted_matrix)[0]):
        values = []
        
        if k == j:
            conc_matrix.append('NaN')
        
        else:
            for i in range(0, np.shape(weighted_matrix)[1]):
               
                caso = weighted_matrix[j][i]
                caso_comp = weighted_matrix[k][i]
                
                if i == 1:
                    if caso < caso_comp:
                        values.append(pesos[i])
                else:
                    if caso > caso_comp:
                        values.append(pesos[i])
                        
                if caso == caso_comp:
                    values.append(pesos[i]*0.5)
                
            #print(values)
            conc_matrix.append(round(sum(values), 4))

In [142]:
conc_matrix = np.array(conc_matrix)
conc_matrix = np.reshape(conc_matrix, (7, 7))

In [143]:
print(conc_matrix)

[['NaN' '0.362' '0.362' '0.482' '0.645' '0.808' '0.482']
 ['0.638' 'NaN' '0.326' '0.964' '0.808' '0.645' '0.808']
 ['0.638' '0.674' 'NaN' '0.638' '0.904' '0.808' '0.904']
 ['0.518' '0.036' '0.362' 'NaN' '0.808' '0.482' '0.808']
 ['0.355' '0.192' '0.096' '0.192' 'NaN' '0.446' '0.422']
 ['0.192' '0.355' '0.192' '0.518' '0.554' 'NaN' '0.554']
 ['0.518' '0.192' '0.096' '0.192' '0.578' '0.446' 'NaN']]


### Criando Tabela 7: Discordance Matrix

In [144]:
# Inicializando matrizes
disc_matrix = []

# Criando função
for j in range(0, np.shape(weighted_matrix)[0]):
    for k in range(0, np.shape(weighted_matrix)[0]):
        values = []
        
        #soma = 0 # iniciando um contador
        if k == j:
            disc_matrix.append('NaN')
        
        else:
            soma = 0
        
            for x in range(0, np.shape(weighted_matrix)[0]):
                if weighted_matrix[k][i] <= weighted_matrix[j][i]:
                    soma += 1
                
            if soma == np.shape(weighted_matrix)[1]:
                disc_matrix.append(0)
        
            else:
                diferenca_bruta = []
                diferenca_absoluta = []
                numerador = 0
            
                for i in range(0, np.shape(weighted_matrix)[1]):
                    caso = weighted_matrix[j][i]
                    caso_comp = weighted_matrix[k][i]
                
                    diferenca_bruta.append(caso_comp - caso)
                    diferenca_absoluta.append(abs(caso_comp - caso))
                
                    for diff in range(0, np.shape(diferenca_bruta)[0]):
                        if diferenca_bruta[diff] > 0:
                            numerador = max(diferenca_bruta)
                    
                    denominador = max(diferenca_absoluta)
                    #values.append(caso_comp - caso)
        
                if (numerador == 0 or denominador == 0):
                    disc_matrix.append(0)
                else:
                    disc_matrix.append(round(numerador/denominador, 4))
                #print(disc_matrix)

In [145]:
disc_matrix = np.array(disc_matrix)
disc_matrix = np.reshape(disc_matrix, (7, 7))

In [146]:
print(disc_matrix)

[['NaN' '1.0' '0.7012' '0.8499' '0' '0' '0.1847']
 ['0.6985' 'NaN' '0.5433' '0.2378' '0' '0' '0']
 ['1.0' '1.0' 'NaN' '0.5998' '0' '0' '0']
 ['1.0' '1.0' '1.0' 'NaN' '0' '0.0112' '0']
 ['1.0' '1.0' '1.0' '1.0' 'NaN' '1.0' '1.0']
 ['1.0' '1.0' '1.0' '1.0' '0.4234' 'NaN' '0.6762']
 ['1.0' '1.0' '1.0' '1.0' '0.8777' '1.0' 'NaN']]


### Criando Tabela 8: Pure Concordance and Pure Discordance Matrix

#### Substituindo 'NaN's por zeros

In [162]:
# Inicializando matrizes
conc_matrix = []

# Criando função
for j in range(0, np.shape(weighted_matrix)[0]):
    for k in range(0, np.shape(weighted_matrix)[0]):
        values = []
        
        if k == j:
            conc_matrix.append(0)
        
        else:
            for i in range(0, np.shape(weighted_matrix)[1]):
               
                caso = weighted_matrix[j][i]
                caso_comp = weighted_matrix[k][i]
                
                if i == 1:
                    if caso < caso_comp:
                        values.append(pesos[i])
                else:
                    if caso > caso_comp:
                        values.append(pesos[i])
                        
                if caso == caso_comp:
                    values.append(pesos[i]*0.5)
                
            #print(values)
            conc_matrix.append(round(sum(values), 4))

conc_matrix = np.array(conc_matrix)
conc_matrix = np.reshape(conc_matrix, (7, 7))

#### Substituindo 'NaN's por zeros

In [163]:
# Inicializando matrizes
disc_matrix = []

# Criando função
for j in range(0, np.shape(weighted_matrix)[0]):
    for k in range(0, np.shape(weighted_matrix)[0]):
        values = []
        
        #soma = 0 # iniciando um contador
        if k == j:
            disc_matrix.append(0)
        
        else:
            soma = 0
        
            for x in range(0, np.shape(weighted_matrix)[0]):
                if weighted_matrix[k][i] <= weighted_matrix[j][i]:
                    soma += 1
                
            if soma == np.shape(weighted_matrix)[1]:
                disc_matrix.append(0)
        
            else:
                diferenca_bruta = []
                diferenca_absoluta = []
                numerador = 0
            
                for i in range(0, np.shape(weighted_matrix)[1]):
                    caso = weighted_matrix[j][i]
                    caso_comp = weighted_matrix[k][i]
                
                    diferenca_bruta.append(caso_comp - caso)
                    diferenca_absoluta.append(abs(caso_comp - caso))
                
                    for diff in range(0, np.shape(diferenca_bruta)[0]):
                        if diferenca_bruta[diff] > 0:
                            numerador = max(diferenca_bruta)
                    
                    denominador = max(diferenca_absoluta)
                    #values.append(caso_comp - caso)
        
                if (numerador == 0 or denominador == 0):
                    disc_matrix.append(0)
                else:
                    disc_matrix.append(round(numerador/denominador, 4))
                #print(disc_matrix)

disc_matrix = np.array(disc_matrix)
disc_matrix = np.reshape(disc_matrix, (7, 7))

#### Criando matrizes de pura concordância ou pura discordância

In [171]:
# Inicializando matrizes
pure_conc = []
pure_disc = []

for j in range(0, np.shape(conc_matrix)[0]):
    conc = conc_matrix[j, :]
    disc = disc_matrix[j, :]
    
    coluna_conc = conc_matrix[:, j]
    coluna_disc = disc_matrix[:, j]
    
    pure_conc.append(sum(conc) - sum(coluna_conc))
    pure_disc.append(sum(disc) - sum(coluna_disc))

In [172]:
pure_conc = np.array(pure_conc)
pure_conc = np.reshape(pure_conc, (7, 1))
print(pure_conc)

[[ 0.282]
 [ 2.378]
 [ 3.132]
 [ 0.028]
 [-2.594]
 [-1.27 ]
 [-1.956]]


In [173]:
pure_disc = np.array(pure_disc)
pure_disc = np.reshape(pure_disc, (7, 1))
print(pure_disc)

[[-2.9627]
 [-4.5204]
 [-2.6447]
 [-1.6763]
 [ 4.6989]
 [ 3.0884]
 [ 4.0168]]
