## RIM - Reference Ideal Method

This is a methods replication of the following article:

Cables, E., Lamata, M. T., & Verdegay, J. L. (2016). RIM-reference ideal method in multicriteria decision making. *Information Sciences*, *337-338*, 1–10. https://doi.org/10.1016/j.ins.2015.12.011

Each value is derived from that article. Code is mine.
In this code, we're trying to select personell using Reference Ideal Method.
This is a typical multicriteria decision-making (MCDM) problem. RIM is the algorithm used to solve it.

### Importing libraries

In [5]:
import math
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
%config Completer.use_jedi = False # this speeds up autocomplete in jupyter

### Creating data, ranges, references and weights (p. 6)

In [8]:
# Inputting data
age       = np.array([30, 40, 25, 27, 45])
years_exp = np.array([0, 9, 0, 0, 15])
sanctions = np.array([2, 1, 3, 5, 2])
mechanics = np.array([3, 3, 1, 3, 2])
phy_limit = np.array([3, 2, 3, 3, 3])
emot_stab = np.array([2, 2, 2, 1, 4])

initial_matrix = np.stack((age, years_exp, sanctions, mechanics, phy_limit, emot_stab),
                          axis = 1)

initial_matrix

array([[30,  0,  2,  3,  3,  2],
       [40,  9,  1,  3,  2,  2],
       [25,  0,  3,  1,  3,  2],
       [27,  0,  5,  3,  3,  1],
       [45, 15,  2,  2,  3,  4]])

In [9]:
# Range values

age_ran       = np.array(range(23, 61))
years_exp_ran = np.array(range(0, 16))
sanctions_ran = np.array(range(0, 11))
mechanics_ran = np.array(range(1, 4))
phy_limit_ran = np.array(range(1, 4))
emot_stab_ran = np.array(range(1, 6))

range_matrix = np.array([age_ran, years_exp_ran, sanctions_ran, mechanics_ran, phy_limit_ran, emot_stab_ran], 
                        dtype = object)

range_matrix

array([array([23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
       57, 58, 59, 60]),
       array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]),
       array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
       array([1, 2, 3]), array([1, 2, 3]), array([1, 2, 3, 4, 5])],
      dtype=object)

In [10]:
# Reference values

age_ref       = np.array(range(30, 36))
years_exp_ref = np.array(range(10, 16))
sanctions_ref = np.array([0])
mechanics_ref = np.array([3])
phy_limit_ref = np.array([3])
emot_stab_ref = np.array([4, 5])

ref_matrix = np.array([age_ref, years_exp_ref, sanctions_ref, mechanics_ref, phy_limit_ref, emot_stab_ref], 
                        dtype = object)

ref_matrix

array([array([30, 31, 32, 33, 34, 35]), array([10, 11, 12, 13, 14, 15]),
       array([0]), array([3]), array([3]), array([4, 5])], dtype=object)

In [11]:
# Weight values
age_w       = 0.2262
years_exp_w = 0.2143
sanctions_w = 0.1786
mechanics_w = 0.1429
phy_limit_w = 0.1190
emot_stab_w = 0.1190

weight_matrix = np.stack((age_w, years_exp_w, sanctions_w, mechanics_w, phy_limit_w, emot_stab_w),
                         axis = 0)

weight_matrix

array([0.2262, 0.2143, 0.1786, 0.1429, 0.119 , 0.119 ])

### Normalizing function

In [13]:
# Function

norm_matrix = [] # inicialização

for j in range(0, np.shape(initial_matrix)[-1]): # Para cada coluna j entre 0 e 6
    
    for i in range(0, np.shape(initial_matrix)[0]): # Para cada linha i entre 0 e 5
        
        values = []
        x = initial_matrix[i][j]
        
        A = range_matrix[j][0]
        B = range_matrix[j][-1]
        C = ref_matrix[j][0]
        D = ref_matrix[j][-1]
        
        # Se o valor de x estiver entre valores de referência
        if (x >= C and x <= D):

            x_norm = 1 # x normalizado vira 1
            
            values.append(x_norm) # esse valor é adicionado à lista temporária 'values'
            i += 1
        
        # Se o valor de x for menor que o da referência
        elif (x >= A and x <= C):
            x_norm = 1 - (min(abs(x - C), abs(x - D)) /
                          abs(A - C))
            
            values.append(x_norm) # esse valor é adicionado à lista temporária 'values'
            i += 1
        
        # Se o valor de x for maior que o da referência
        elif (x >= D and x <= B):
            
            x_norm = 1 - (min(abs(x - C), abs(x - D)) /
                             abs(D - B))
            
            values.append(x_norm) # esse valor é adicionado à lista temporária 'values'
            i += 1

        # Tudo na lista 'values' vai para a matriz final 'norm_matrix'
        norm_matrix.append(values)

print(norm_matrix)

[[1], [0.8], [0.2857142857142857], [0.5714285714285714], [0.6], [0.0], [0.9], [0.0], [0.0], [1], [0.8], [0.9], [0.7], [0.5], [0.8], [1], [1], [0.0], [1], [0.5], [1], [0.5], [1], [1], [1], [0.33333333333333337], [0.33333333333333337], [0.33333333333333337], [0.0], [1]]


In [14]:
# Reorganizando 'norm_matrix'
norm_matrix = np.array(norm_matrix)
norm_matrix = np.reshape(norm_matrix, (6, 5)).T

print(norm_matrix)

[[1.         0.         0.8        1.         1.         0.33333333]
 [0.8        0.9        0.9        1.         0.5        0.33333333]
 [0.28571429 0.         0.7        0.         1.         0.33333333]
 [0.57142857 0.         0.5        1.         1.         0.        ]
 [0.6        1.         0.8        0.5        1.         1.        ]]


### Weighting function

In [171]:
weighted_matrix = norm_matrix * weight_matrix

print(weighted_matrix)

[[0.2262     0.         0.14288    0.1429     0.119      0.03966667]
 [0.18096    0.19287    0.16074    0.1429     0.0595     0.03966667]
 [0.06462857 0.         0.12502    0.         0.119      0.03966667]
 [0.12925714 0.         0.0893     0.1429     0.119      0.        ]
 [0.13572    0.2143     0.14288    0.07145    0.119      0.119     ]]


### Indexes function

In [172]:
col_pos = []
col_neg = []
col_r = []


for i in range(0, np.shape(weighted_matrix)[0]):

    line = weighted_matrix[i]

    # I positive
    i_pos = math.sqrt(sum((line - weight_matrix) ** 2))

    col_pos.append(i_pos)

    # I negative
    i_neg = math.sqrt(sum((line ** 2)))

    col_neg.append(i_neg)

    # R
    r = i_neg / (i_neg + i_pos)

    col_r.append(r)

    i += 1

In [187]:
letters = ['A', 'B', 'C', 'D', 'E']
indexes = np.stack((letters, col_pos, col_neg, col_r),
                   axis = 1)

print(indexes)

[['A' '0.23128810211028533' '0.3282316085395257' '0.5866310020755594']
 ['B' '0.11251182105795718' '0.348305628068862' '0.755842967163786']
 ['C' '0.31877079651120804' '0.18852399605711312' '0.3716261211802666']
 ['D' '0.2783125896380191' '0.24344056559988483' '0.4665818752718097']
 ['E' '0.12069652563350779' '0.34378220620037914' '0.740146281495031']]
