## Lendo bibliotecas

In [2]:
import math
import numpy as np
import pandas as pd
%config Completer.use_jedi = False # this speeds up autocomplete

## Replicando "Multi-criteria decision-making in the selection of a renewable energy project in Spain: The Vikor method"

In [75]:
nome_ab_energia = [
    'A1', 'A2', 'A3', 'A4',
    'A5', 'A6', 'A7', 'A8',
    'A9', 'A10', 'A11', 'A12', 'A13']

nome_energia = [
    'Wind power P≤5 MW',
    'Wind power 5 ≤ P ≤10 MW',
    'Wind power 10 ≤ P ≤ 50 MW',
    'Hydroelectric P ≤ 10 MW',
    'Hydroelectric 10 ≤ P ≤ 25 MW',
    'Hydroelectric 25 ≤ P ≤ 50 MW',
    'Solar Thermo-electric P ≤ 10 MW',
    'Biomass (energetic cultivations) P ≤ 5 MW',
    'Biomass (forest and agricultural wastes) P ≤ 5 MW',
    'Biomass (farming industrial wastes) P ≤ 5 MW',
    'Biomass (forest industrial wastes) P ≤ 5 MW',
    'Biomass (co-combustion in conventional central) P ≤ 50 MW',
    'Bio fuels P ≤ 2 MW'
]

nome_colunas = ['Power',
                'Invest. Ratio',
                'Implement. Period',
                'Op. Hours',
                'Useful Life',
                'Op&Maint Costs',
                'tCO2/y']

criteria = ['+',
            '-',
            '-',
            '+',
            '+',
            '-',
            '+']

weight = [0.32, 0.09, 0.03, 0.12, 0.13, 0.04, 0.27]

matrix = [
    [ 5000,  937,   1, 2350, 20, 1.470, 1929936],
    [10000,  937,   1, 2350, 20, 1.470, 3216560],
    [25000,  937,   1, 2350, 20, 1.510, 9649680],
    [ 5000, 1500, 1.5, 3100, 25, 1.450,  472812],
    [20000,  700,   2, 2000, 25, 0.700,  255490],
    [35000,  601, 2.5, 2000, 25, 0.600,  255490],
    [50000, 5000,   2, 2596, 25, 4.200,  482856],
    [ 5000, 1803,   1, 7500, 15, 7.106, 2524643],
    [ 5000, 1803,   1, 7500, 15, 5.425, 2524643],
    [ 5000, 1803,   1, 7500, 15, 5.425, 2524643],
    [ 5000, 1803,   1, 7500, 15, 2.813, 2524643],
    [56000,  856,   1, 7500, 20, 4.560, 4839548],
    [ 2000, 1503, 1.5, 7000, 20, 2.512, 5905270]
]

# Transformando matriz em dataframe
df = pd.DataFrame(matrix,
                  columns = nome_colunas,
                  index = nome_ab_energia)

df

Power  Invest. Ratio  Implement. Period  Op. Hours  Useful Life  \
A1    5000            937                1.0       2350           20   
A2   10000            937                1.0       2350           20   
A3   25000            937                1.0       2350           20   
A4    5000           1500                1.5       3100           25   
A5   20000            700                2.0       2000           25   
A6   35000            601                2.5       2000           25   
A7   50000           5000                2.0       2596           25   
A8    5000           1803                1.0       7500           15   
A9    5000           1803                1.0       7500           15   
A10   5000           1803                1.0       7500           15   
A11   5000           1803                1.0       7500           15   
A12  56000            856                1.0       7500           20   
A13   2000           1503                1.5       7000           20   

     Op&Maint Costs   tCO2/y  
A1            1.470  1929936  
A2            1.470  3216560  
A3            1.510  9649680  
A4            1.450   472812  
A5            0.700   255490  
A6            0.600   255490  
A7            4.200   482856  
A8            7.106  2524643  
A9            5.425  2524643  
A10           5.425  2524643  
A11           2.813  2524643  
A12           4.560  4839548  
A13           2.512  5905270

#### Criando Sj para todos os critérios de todas as alternativas

In [76]:
# Hiperparâmetros
matrix = np.array(matrix).T

n_columns = np.shape(matrix)[0]
n_lines = np.shape(matrix)[1]

Sj_temp_list = []

# Definindo valores
for j in range(n_columns):
    for i in range(n_lines):
        
        if (criteria[j] == '-'):

            Fi_plus = min(matrix[j]) # highest criteria value
            Fi_minus = max(matrix[j]) # lowest criteria value
        
        else:
            Fi_plus = max(matrix[j]) # highest criteria value
            Fi_minus = min(matrix[j]) # lowest criteria value
        
        w = weight[j]
        case = matrix[j][i] # case value
        
        Sj = w * (Fi_plus - case)/(Fi_plus - Fi_minus)
        Sj_temp_list.append(Sj)

# Criando Sj e Rj
Sj_temp_list = [round(num, 3) for num in Sj_temp_list]
Sj_temp_list = np.reshape(Sj_temp_list, (n_columns, n_lines)).T

print(Sj_temp_list)

[[ 0.302  0.007 -0.     0.112  0.065  0.005  0.222]
 [ 0.273  0.007 -0.     0.112  0.065  0.005  0.185]
 [ 0.184  0.007 -0.     0.112  0.065  0.006  0.   ]
 [ 0.302  0.018  0.01   0.096  0.     0.005  0.264]
 [ 0.213  0.002  0.02   0.12   0.     0.001  0.27 ]
 [ 0.124 -0.     0.03   0.12   0.    -0.     0.27 ]
 [ 0.036  0.09   0.02   0.107  0.     0.022  0.263]
 [ 0.302  0.025 -0.     0.     0.13   0.04   0.205]
 [ 0.302  0.025 -0.     0.     0.13   0.03   0.205]
 [ 0.302  0.025 -0.     0.     0.13   0.03   0.205]
 [ 0.302  0.025 -0.     0.     0.13   0.014  0.205]
 [ 0.     0.005 -0.     0.     0.065  0.024  0.138]
 [ 0.32   0.018  0.01   0.011  0.065  0.012  0.108]]


#### Criando Sj e Rj para cada alternativa

In [77]:
# Inicializando Sj_list e Rj_list
Sj_list = []
Rj_list = []

# Criando Sj e Rj
for i in range(n_lines):
    Sj = sum(Sj_temp_list[i])
    Sj_list.append(Sj)
    
    Rj = max(Sj_temp_list[i])
    Rj_list.append(Rj)

df['S'] = [round(num, 2) for num in Sj_list]
df['R'] = [round(num, 2) for num in Rj_list]

# Visualizando 'Tabela S e R'
df[['S', 'R']].T

A1    A2    A3   A4    A5    A6    A7   A8    A9   A10   A11   A12   A13
S  0.71  0.65  0.37  0.7  0.63  0.54  0.54  0.7  0.69  0.69  0.68  0.23  0.54
R  0.30  0.27  0.18  0.3  0.27  0.27  0.26  0.3  0.30  0.30  0.30  0.14  0.32

#### Criando Qj

In [78]:
# Inicializando Qj_list e definindo valor de 'v'
v_list = np.arange(0, 1.1, 0.1)

columns = []
Q_compare = pd.DataFrame(columns = columns)
row_index = 0

# Criando Qj
for n in range(len(v_list)):
    Qj_list = []

    v = v_list[n]
    Q_compare.loc[row_index, 'v'] = v # cria uma coluna com o valor de 'v' atual
    
    for i in range(n_lines):
        S_min = min(Sj_list)
        S_max = max(Sj_list)
        R_min = min(Rj_list)
        R_max = max(Rj_list)

        diff_S = S_max - S_min
        diff_R = R_max - R_min

        S = Sj_list[i]
        R = Rj_list[i]

        Qj = (v * ((S - S_min)/diff_S)) + (1 - v) * ((R - R_min)/diff_R)

        Qj_list.append(Qj)
        
    for alt in range(len(Qj_list)):
        Q_compare.loc[row_index,
                      nome_ab_energia[alt]] = round(Qj_list[alt], 3)
    
    row_index += 1

Q_compare

v     A1     A2     A3     A4     A5     A6     A7     A8     A9    A10  \
0   0.0  0.901  0.742  0.253  0.901  0.725  0.725  0.687  0.901  0.901  0.901   
1   0.1  0.911  0.754  0.257  0.907  0.735  0.718  0.682  0.909  0.907  0.907   
2   0.2  0.921  0.766  0.261  0.913  0.744  0.710  0.677  0.916  0.912  0.912   
3   0.3  0.931  0.778  0.265  0.920  0.753  0.702  0.672  0.924  0.918  0.918   
4   0.4  0.941  0.790  0.270  0.926  0.763  0.695  0.667  0.932  0.923  0.923   
5   0.5  0.951  0.802  0.274  0.932  0.772  0.687  0.661  0.939  0.929  0.929   
6   0.6  0.960  0.814  0.278  0.938  0.782  0.679  0.656  0.947  0.934  0.934   
7   0.7  0.970  0.826  0.282  0.944  0.791  0.672  0.651  0.954  0.940  0.940   
8   0.8  0.980  0.839  0.287  0.950  0.800  0.664  0.646  0.962  0.945  0.945   
9   0.9  0.990  0.851  0.291  0.956  0.810  0.656  0.641  0.970  0.951  0.951   
10  1.0  1.000  0.863  0.295  0.963  0.819  0.649  0.636  0.977  0.956  0.956   

      A11  A12    A13  
0   0.901  0.0  1.000  
1   0.903  0.0  0.965  
2   0.905  0.0  0.930  
3   0.908  0.0  0.895  
4   0.910  0.0  0.859  
5   0.912  0.0  0.824  
6   0.914  0.0  0.789  
7   0.916  0.0  0.754  
8   0.919  0.0  0.719  
9   0.921  0.0  0.684  
10  0.923  0.0  0.649

#### Acceptable advantage (C1) and acceptable stability (C2)

In [79]:
# Selecionando apenas valores com 'v = 0.5'
Q_05 = Q_compare.T
Q_05 = Q_05.drop('v', axis = 0)[[5]]
Q_05 = Q_05[5].tolist()

df['S'] = [round(num, 2) for num in Sj_list]
df['R'] = [round(num, 2) for num in Rj_list]
df['Q'] = [round(num, 2) for num in Q_05]

df = df.sort_values(by = 'Q')
df['Rank'] = range(1, n_lines + 1)
df

Power  Invest. Ratio  Implement. Period  Op. Hours  Useful Life  \
A12  56000            856                1.0       7500           20   
A3   25000            937                1.0       2350           20   
A7   50000           5000                2.0       2596           25   
A6   35000            601                2.5       2000           25   
A5   20000            700                2.0       2000           25   
A2   10000            937                1.0       2350           20   
A13   2000           1503                1.5       7000           20   
A11   5000           1803                1.0       7500           15   
A4    5000           1500                1.5       3100           25   
A9    5000           1803                1.0       7500           15   
A10   5000           1803                1.0       7500           15   
A8    5000           1803                1.0       7500           15   
A1    5000            937                1.0       2350           20   

     Op&Maint Costs   tCO2/y     S     R     Q  Rank  
A12           4.560  4839548  0.23  0.14  0.00     1  
A3            1.510  9649680  0.37  0.18  0.27     2  
A7            4.200   482856  0.54  0.26  0.66     3  
A6            0.600   255490  0.54  0.27  0.69     4  
A5            0.700   255490  0.63  0.27  0.77     5  
A2            1.470  3216560  0.65  0.27  0.80     6  
A13           2.512  5905270  0.54  0.32  0.82     7  
A11           2.813  2524643  0.68  0.30  0.91     8  
A4            1.450   472812  0.70  0.30  0.93     9  
A9            5.425  2524643  0.69  0.30  0.93    10  
A10           5.425  2524643  0.69  0.30  0.93    11  
A8            7.106  2524643  0.70  0.30  0.94    12  
A1            1.470  1929936  0.71  0.30  0.95    13

In [84]:
Q = df['Q'].tolist()
S = df['S'].tolist()
R = df['R'].tolist()

C1 = []
C2 = []

for i in range(n_lines):
    if i == n_lines - 1:
        C1.append('No')
        C2.append('No')
        
    else:
        Q_a1 = Q[i]
        S_a1 = S[i]
        R_a1 = R[i]

        Q_a2 = Q[i + 1]
        S_a2 = S[i + 1]
        R_a2 = R[i + 1]

        DQ = 1/(n_lines - 1)

        if (Q_a2 - Q_a1 >= DQ):
            C1.append('Yes')
        else:
            C1.append('No')

        if (S_a1 < S_a2) or (R_a1 < R_a2):
            C2.append('Yes')
        else:
            C2.append('No')
        
df['C1'] = C1
df['C2'] = C2
df

Power  Invest. Ratio  Implement. Period  Op. Hours  Useful Life  \
A12  56000            856                1.0       7500           20   
A3   25000            937                1.0       2350           20   
A7   50000           5000                2.0       2596           25   
A6   35000            601                2.5       2000           25   
A5   20000            700                2.0       2000           25   
A2   10000            937                1.0       2350           20   
A13   2000           1503                1.5       7000           20   
A11   5000           1803                1.0       7500           15   
A4    5000           1500                1.5       3100           25   
A9    5000           1803                1.0       7500           15   
A10   5000           1803                1.0       7500           15   
A8    5000           1803                1.0       7500           15   
A1    5000            937                1.0       2350           20   

     Op&Maint Costs   tCO2/y     S     R     Q  Rank   C1   C2  
A12           4.560  4839548  0.23  0.14  0.00     1  Yes  Yes  
A3            1.510  9649680  0.37  0.18  0.27     2  Yes  Yes  
A7            4.200   482856  0.54  0.26  0.66     3   No  Yes  
A6            0.600   255490  0.54  0.27  0.69     4   No  Yes  
A5            0.700   255490  0.63  0.27  0.77     5   No  Yes  
A2            1.470  3216560  0.65  0.27  0.80     6   No  Yes  
A13           2.512  5905270  0.54  0.32  0.82     7  Yes  Yes  
A11           2.813  2524643  0.68  0.30  0.91     8   No  Yes  
A4            1.450   472812  0.70  0.30  0.93     9   No   No  
A9            5.425  2524643  0.69  0.30  0.93    10   No   No  
A10           5.425  2524643  0.69  0.30  0.93    11   No  Yes  
A8            7.106  2524643  0.70  0.30  0.94    12   No  Yes  
A1            1.470  1929936  0.71  0.30  0.95    13   No   No